name: Build OpenWrt
run-name: Build openwrt ${{inputs.source_ver}} for ${{inputs.device}}

on:
  workflow_dispatch:
    inputs:
      device:
        description: '要编译的设备型号'
        required: true
        default: 'PHICOMM-K3'
        type: choice
        options:
          - RM2100
          - RM2100-MT
          - MI-MINI
          - PHICOMM-K3
      password:
        description: '登录密码和WiFi密码。'
        type: string
        default: 'password'
      gateway:
        description: '网关'
        type: string
        default: '192.168.2.1'
      ssid:
        description: 'WIFI SSID'
        type: string
        default: 'OpenWrt'
      pppoe_username:
        description: 'PPPOE (宽带) 用户名'
        type: string
      pppoe_password:
          description: 'PPPOE (宽带) 密码'
          type: string
      source_ver:
        description: '源码版本 (分支)'
        type: string
        default: 'v23.05.0'
      k3_wifidriver:
        description: 'PHICOMM-K3的WIFI驱动'
        default: 'ac88u_20'
        type: choice
        options:
          - '69027'
          - ac88u_16
          - ac88u_19
          - ac88u_20
          - asus-dhd24
          - ea9500_175339
          - ea9500_179240
          - k3
          - r8500
      upload_bin:
        description: '上传BIN文件夹'
        type: boolean
        default: false
      upload_firmware:
        description: '上传FIRMWARE文件夹'
        type: boolean
        default: true

env:
  SOURCE_URL: https://github.com/openwrt/openwrt.git
  FEEDS_CONF: feeds.conf.default
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq -y update  
        sudo -E apt-get -qq -y install openssl binutils bzip2 diff find flex gawk gcc-6+ getopt grep install libc-dev libz-dev make4.1+ perl python3.6+ rsync subversion unzip which
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone -b ${{inputs.source_ver}} --single-branch ${{env.SOURCE_URL}} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cp -a $GITHUB_WORKSPACE/files/miwifi-mini/default-settings $GITHUB_WORKSPACE/openwrt/packages/


    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: |
        cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        # 拷贝配置文件
        cp configs/${{inputs.device}}.config openwrt/.config

        # 修改ROOT密码
        passwd=$(openssl passwd -salt 'OR/e/lZS' ${{inputs.password}})
        sed -i "s/root:::0:99999:7:::/root:${passwd}:19633:0:99999:7:::/g" openwrt/package/base-files/files/etc/passwd
        sed -i "s/root:::0:99999:7:::/root:${passwd}:19633:0:99999:7:::/g" openwrt/package/base-files/files/etc/shadow

        # 修改网关
        sed -i 's/192.168.1.1/${{inputs.gateway}}/g' openwrt/package/base-files/files/bin/config_generate

        # PPPOE
        if [[ ! -z "${{inputs.pppoe_username}}" && ! -z "${{inputs.pppoe_password}}" ]];then
          sed -i "/exit 0/i\uci set network.globals.ula_prefix=''" openwrt/package/default-settings/files/zzz-default-settings
          sed -i "/exit 0/i\uci set network.wan.username='${{inputs.pppoe_username}}'" openwrt/package/default-settings/files/zzz-default-settings
          sed -i "/exit 0/i\uci set network.wan.password='${{inputs.pppoe_password}}'" openwrt/package/default-settings/files/zzz-default-settings
          sed -i "/exit 0/i\uci set network.wan.proto='pppoe'" openwrt/package/default-settings/files/zzz-default-settings
          sed -i "/exit 0/i\uci commit network" openwrt/package/default-settings/files/zzz-default-settings
        fi

        # 默认开启Turboacc的BBR
        if grep -q "CONFIG_PACKAGE_luci-app-turboacc=y" openwrt/.config;then sed -i "s/option bbr_cca '0'/option bbr_cca '1'/g" openwrt/package/feeds/luci/luci-app-turboacc/root/etc/config/turboacc;fi

        # 修改adguardhome,只编译二进制文件,不要配置文件
        if grep -q "CONFIG_PACKAGE_luci-app-adguardhome_INCLUDE_binary=y" openwrt/.config; then sed -i -e "67,71d" -e "47,50d" openwrt/feeds/packages/net/adguardhome/Makefile;fi

        # 修改WIFI配置
        sed -i "/exit 0/i\uci set wireless.default_radio0.ssid='${{inputs.ssid}}'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci set wireless.default_radio0.encryption='psk-mixed'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci set wireless.default_radio0.key='${{inputs.password}}'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci set wireless.radio1.htmode='VHT80'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci set wireless.default_radio1.ssid='${{inputs.ssid}}'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci set wireless.default_radio1.encryption='psk-mixed'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci set wireless.default_radio1.key='${{inputs.password}}'" openwrt/package/default-settings/files/zzz-default-settings
        sed -i "/exit 0/i\uci commit wireless" openwrt/package/default-settings/files/zzz-default-settings

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_OUTPUT
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: 上传bin目录
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && ${{inputs.upload_bin}}
      with:
        name: OpenWrt_bin${{ steps.compile.outputs.DEVICE_NAM }}_${{inputs.source_ver}}${{ steps.compile.outputs.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: inputs.upload_firmware && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ steps.compile.outputs.DEVICE_NAME }}_${{inputs.source_ver}}${{ steps.compile.outputs.FILE_DATE }}
        path: ${{ steps.organize.outputs.FIRMWARE }}
